name: 'Trybe Serverless Deploy'
author: 'Trybe'
description: 'Action utilizada para voltar a versão de uma aplicação serverless na Trybe.'
inputs:
  environment:
    description: 'Environment no qual esta função serverless será deployada.'
    required: true
  settings:
    description: 'Configurações em YAML sobre como configurar este deploy, codificado em base64.'
    required: false
  command:
    description: 'Comando à ser executado.'
    default: deploy
runs:
  using: 'composite'
  steps:
    - id: job
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        SERVERLESS_SETTINGS: ${{ inputs.settings }}
        COMMAND: ${{ inputs.command }}
